### ISSUE TITLE
Status of the walletobjects API?

### ISSUE THREAD

**Issue by mladenilic** [google-pay/passes-rest-samples#1]
With the s2ap-quickstart-{ruby,php,python,charp} repos removed, I'm concerned as to what's the long term plan for the walletobjects API and for the wallet passes in general?

Also, is there a way to obtain discovery document for this api, since it is not supported by api client libraries?

**Comment by mladenilic** [comment]
I'm sorry for being persistent here, but it would really help me a lot if someone could point me in the direction where I can get much needed answers regarding walletobjects api.

The `wobs-discovery.json`  file that was available in the `s2ap-quickstart-ruby` repo is outdated and it is missing the declarations for `callbackOptions` parameters. Is there a way to obtain the new discovery document?

Thanks!

**Comment by angelbarranco** [comment]
This was deprecated. The [rest API](https://developers.google.com/pay/passes/reference/v1/) is the suggested way to integrate with the Pay for Passes API.

**Comment by mladenilic** [comment]
Hi @angelbarranco, thanks for the reply.

I'm not exactly sure what are you referring to when you say "This was deprecated". Examples from this repo all use the rest api you linked to, same as s2ap projects were (or at least ruby one did).

https://developers.google.com/pay/passes/support/libraries#libraries

In the link above the ruby sdk is missing. In order to build the sdk myself I need the discovery json document, which I mentioned in my previous comment. Since the walletobjects api is "private", I don't know where can I get it:

https://developers.google.com/apis-explorer/#p/discovery/v1/discovery.apis.getRest?api=walletobjects&version=v1&_h=9&

Anyway, I hope it's clear now where the first two comments about.

Cheers!

**Comment by angelbarranco** [comment]
Hey @mladenilic,
It is missing because have deprecated the ruby SDK for the Google Pay for Passes API. In the link you provided you can see the currently supported SDKs.

**Comment by angelbarranco** [comment]
@mladenilic,

As an update here is the discovery doc you requested: https://walletobjects.googleapis.com/$discovery/rest?version=v1.

We are updating the dev docs to make this clear.

**Comment by mladenilic** [comment]
@angelbarranco Thanks.

Looking forward to the documentation update.
