### ISSUE TITLE
Missing items from C# Library mentioned in samples

### ISSUE THREAD

**Issue by faceoffers28** [google-pay/passes-rest-samples#16]
There appears to be some missing items in the C# Library found here.

[](https://developers.google.com/pay/passes/support/libraries#libraries)

Both OfferClass and OfferObject is missing IssuerData. Perhaps this is an oversight or perhaps this is on purpose. The documentation shows IssuerData, so I assume it's an oversight.

Hope this helps.

**Comment by angelbarranco** [comment]
Offer objects and classes are linked to an issuer through an [id field](https://developers.google.com/pay/passes/rest/v1/offerobject#OfferObject.FIELDS.id).

Is this what you are referring to?

**Comment by faceoffers28** [comment]
Perhaps. issuerData is mentioned in the documentation for both the OfferClass and the OfferObject as shown here. https://developers.google.com/pay/passes/guides/pass-verticals/offers/code-snippets#json-offerclass 

IssuerData is not found in the C# Library for OfferClass and OfferObject.

**Comment by angelbarranco** [comment]
The field is deprecated. Let me update the docs. Thanks for bringing this up.
