### ISSUE TITLE
Nodejs is bitterly missed

### ISSUE THREAD

**Issue by s-a** [google-pay/passes-rest-samples#17]
:(

**Comment by mladenilic** [comment]
Hi @s-a, I'm not a member of this organization, but I had my fair share of frustration with the walletobjects api.

You can generate it yourself using discovery service.  People having the same problem with ruby client as well - https://github.com/googleapis/google-api-ruby-client/issues/747.

Based on a quick test, nodejs seems even worse, as it will require you to fork the client itself, but `npm run generate ./wobs-discovery.json` should do the trick.

Hope it helps!

**Comment by s-a** [comment]
@mladenilic well at the end it was not so hard to implement with Node. Currently iam looking for a solution to validate data against JSON schema, I found https://walletobjects.googleapis.com/$discovery/rest?version=v1 and tried against `Ajv`, but without success so far. @angelbarranco is there a valid JSON schema regarding https://json-schema.org/ for passes json data available?

**Comment by angelbarranco** [comment]
Hey @s-a ,

Please try with Schema Draft 6, [Ajv instructions](https://github.com/epoberezkin/ajv).

**Comment by s-a** [comment]
@angelbarranco well i think it should be 7. Tried your suggestion but then it fails to compile with `unknown datatype` `double` and `int64`. Are you familiar with `ajv` ? The prolem is that all validations always return a valid result even if I pass badly wrong data in validation.

**Comment by s-a** [comment]
Well this is not a valid json schema. I came to the solution to generate one based on the discovery document. But is a poor solution. For example the required information for properties is only available in comments as text form. Does there exist a valid JSON schema some where?

**Comment by angelbarranco** [comment]
Hey @s-a,

I have not used it before. I do see that now. Wallet objects API does not have official libraries for node nor strict adherence to [JSON schema validator](https://developers.google.com/discovery/v1/reference/apis) for the discovery document. It is used by our tools to explore the API. So I do not know of any valid JSON schema.

The library for node.js is something we are looking at for the future though.

**Comment by s-a** [comment]
@angelbarranco thank you. Can you point me to a place where I can submit a request for a JSON schema? I think this kind of document will bring good benefits for this API

**Comment by angelbarranco** [comment]
Sure. You can submit it [here](https://support.google.com/pay/merchants/contact/instore_merchant_support?visit_id=637015668081569274-2237198751&rd=1).
