### ISSUE TITLE
I noticed that the guava dependency resolves to the android version. I changed to the jre version and now the error is different:

### ISSUE THREAD

**Issue by whitemike889** [google-pay/passes-rest-samples#24]
I noticed that the guava dependency resolves to the android version. I changed to the jre version and now the error is different:
Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;C)V"}}

Looks like it is the same issue as SeleniumHQ/selenium#3880. Either it is reappearing or it has not been solved as mentioned there.

Another unsolved similar issue: https://groups.google.com/forum/#!topic/selenium-users/U7bOqbZ7vAk

_Originally posted by @Elatec-RFID in https://github.com/google-pay/passes-rest-samples/issues/23#issuecomment-628581681_

**Comment by angelbarranco** [comment]
use 
`compile group: 'com.google.api-client', name: 'google-api-client', version: '1.23.0'`
as per the [sample project](https://github.com/google-pay/passes-rest-samples/blob/master/java/build.gradle)
