### ISSUE TITLE
Google Event Ticket Logo as Base64 string

### ISSUE THREAD

**Issue by shailu0287** [google-pay/passes-rest-samples#26]
I don't have a URL for logo that is publically available. Is there any possibility that I can use base64 string for logo.

**Comment by ncalteen** [comment]
Hello,

I apologize, but this repository is being archived and replaced by [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples) going forward. If you still have a question, please open a new issue in that repository.

Thank you!
