### ISSUE TITLE
Java language copy jar version issues

### ISSUE THREAD

**Issue by Chaithanya-Bangaru** [google-pay/passes-rest-samples#27]
Hi,
Am unable to even compile the java language version of the project. More version documentation is needed.

- Which of these versions need to be used ? google-walletobjects-v1-rev_20200326-java.jar OR google-walletobjects-v1-rev_20200922-java.jar
- I tried to download these versions from maven as I'm comfortable with mvn build instead of gradle but failing at compilation itslef
- If this is built in gradle successfully, can u please specify the gradle version ?

**Comment by ncalteen** [comment]
Hello,

I apologize, but this repository is being archived and replaced by [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples) going forward. If you still have a question, please open a new issue in that repository.

Thank you!
