### ISSUE TITLE
Google Pay Clarifiation

### ISSUE THREAD

**Issue by krishnakumar-k** [google-pay/passes-rest-samples#29]
Hi,

I can able to generate the token successfully and able to preview the pass in the chrome browser. I have a few clarifications 
in below.

1. Is there any possibility to open an android app without a browser?
2. Is there any possibility to add multiple labels to the Loyalty card?
3. Is there any to use three different colors in (Background, Label, and value)colors?

https://pay.google.com/gp/v/save/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb29nbGUiLCJ0eXAiOiJzYXZldG9hbmRyb2lkcGF5IiwiaXNzIjoiY292aWQxOWdvb2dsZXdhbGxldEBlbmhhbmNlZC1lbWJsZW0tMzA0NTE1LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwib3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjgwODAiXSwiaWF0IjoxNjE0NDQ3NDY4LCJwYXlsb2FkIjp7ImxveWFsdHlPYmplY3RzIjpbeyJpZCI6IjMzODgwMDAwMDAwMTAxMDgwNzcuTE9ZQUxUWV9PQkpFQ1RfNGFjNzJhZTItM2ZkZi00NGQ0LWFkNGMtYTcxODIwMDUzYzI4In1dfX0.WoZ0fLeuDROAZ9SfSxYFJIxr1u6tLGzGDKLV0En9RlhnG5V142jFtL2aajN-48orAO5vHbPWAw20K1jRPDnfREfdc1iqruc1Txe0XwhS0NIvPBtmoQQNM5iL4ubXTb9j5jbYMrV5z0uIP6Wq1LFypKWfRXffK3NB5AWRsvgai-e7GzbB_XJbRXboSNjTk8waXZgsklonSbVml4if0OsOjddsY_wDdaXXXuYijtTGXztknPlbsHGntE4kIc_ho5HcOjtGy8CioU6ei0A70UOCR9sREqhmJRcPqhXv3nA70ANR0xgQ2jPjhsR-BUclVQjgZ_jWGWOTk5zyGspOTJwP2w

Thanks

**Comment by ncalteen** [comment]
Hello,

I apologize, but this repository is being archived and replaced by [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples) going forward. If you still have a question, please open a new issue in that repository.

Thank you!
