### ISSUE TITLE
Java example uses outdated client library

### ISSUE THREAD

**Issue by carstenhag** [google-pay/passes-rest-samples#3]
The lib used in this repo is from 2018, but on https://developers.google.com/pay/passes/support/libraries#libraries there's a library from 2019-05-23. In that version, ValidTimeInterval has been fixed for OfferObjects (and probably other stuff I haven't noticed yet).

**Comment by stephenmcd** [comment]
Hi, that's updated now in 6dc20395d4dd99559a903571b6107e06e135d866 and 4704d6db105b59149fde1195de4e547fab24d93c

Thanks

**Comment by carstenhag** [comment]
Thanks! 👍
