### ISSUE TITLE
Path to file with private key and Google credential config

### ISSUE THREAD

**Issue by prajapati-ritesh** [google-pay/passes-rest-samples#30]
Hi,

I am trying to generate Google Pass using the source code (google-pay/passes-rest-samples).

Please let me know what values need to pass as private key and Google credential config value in privatekey.json file.

Also from where we will get project_id, private_key_id and private_key which needs to set in privatekey.json file.

Thanks and Regards,
Ritesh V. Prajapati.

**Comment by ncalteen** [comment]
Hello,

I apologize, but this repository is being archived and replaced by [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples) going forward. If you still have a question, please open a new issue in that repository.

The updated samples and README files in that repository contain a more detailed walkthrough of setting up credentials. Please take a look and, if you run into any blockers, open an issue in the new repo and I'll take a look!

Thank you!
