### ISSUE TITLE
SVG image as Logo

### ISSUE THREAD

**Issue by prajapati-ritesh** [google-pay/passes-rest-samples#32]
Hi,

I have logo uri with file extension .svg. Google Pass link is generated but it is giving error when I open link in browser.
My logo object for one of the google pass request is mentioned below. I am using .svg file link instead of .png or .jpg file.

Can we use .svg extension file as a logo? If yes please provide solution here.

"Logo": {
        "SourceUri": {
            "Uri": "https:/xxxxx/imagename.svg",
            "Description": "Test Description"
        }
    }

**Comment by ncalteen** [comment]
Hello,

I apologize, but this repository is being archived and replaced by [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples) going forward. If you still have a question, please open a new issue in that repository.

Thank you!
