### ISSUE TITLE
[PHP] Google_Service_Walletobjects_* from docs

### ISSUE THREAD

**Issue by zertex** [google-pay/passes-rest-samples#34]
I can not find Google_Service_Walletobjects_* in
`composer require google/apiclient:"^2.4"`

Where it?

**Comment by ncalteen** [comment]
Hello,

The Walletobjects library is available as a separate download here:

https://developers.google.com/wallet/generic/resources/libraries#php

I apologize, but this repository is being archived and replaced by [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples) going forward. If you still have a question, please open a new issue in that repository.

Thank you!
