### ISSUE TITLE
Facing Issue in Save to Phone URL

### ISSUE THREAD

**Issue by tahaqutbuddin** [google-pay/passes-rest-samples#36]
After executing main.php in terminal, as soon as I open the link in browser it says, Something went wrong.

**Comment by mickaelxd** [comment]
Hey @tahashakir, i'm facing the same issue. Did you solved?

**Comment by tahaqutbuddin** [comment]
@mickaelxd 
no man not yet. But I have contacted Google Support for it. 
Will let you know if I get some positive news on it.

**Comment by ncalteen** [comment]
Hello,

I apologize, but this repository is being archived and replaced by [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples) going forward. If you still have a question, please open a new issue in that repository.

In good news, the PHP samples there have been updated so this should no longer be an issue!

Thank you!
