### ISSUE TITLE
Can't find passes in Google Pay after clicking on Save

### ISSUE THREAD

**Issue by dynasigncorp** [google-pay/passes-rest-samples#37]
I have been trying to find out why I can't see the passes I saved to Google Pay. But I just can't find it in Google Pay.
Anything I might have done wrong?   Any suggestion I shall try or look for?
I set  ReviewStatus to  draft, and use developer account in both  Chrome (to save), and Google pay (to check on passes).  I can't find it.
And I set ReveiwStatus to  underReview,  I still can't find it in Google Pay.
I am so frustrated.

**Comment by ncalteen** [comment]
Hello,

I apologize, but this repository is being archived and replaced by [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples) going forward. If you still have a question, please open a new issue in that repository.

Thank you!
